import Image from 'next/image'

import Link from 'next/link'
import './style.css'
import { Inter } from 'next/font/google'
import logo from '../images/logo.svg'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header className='header'>
          <div className='header__container'>
            <Link href='/'>
              <Image width={154} height={42} className='header__logo' src={logo} alt='логотип Максимум' />
            </Link>
            <hr className='header__line' />
            <h1 className='header__title'>Официальный дилер Максимум </h1>
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
